apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-demo
  namespace: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-demo
  template:
    metadata:
      labels:
        app: react-demo
    spec:
      containers:
        - name: react-demo
          image: theblackantjsc/react-demo:v3
          ports:
            - containerPort: 80
