apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: react-demo
  namespace: demo
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: react.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: react-demo
                port:
                  number: 80
